/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroPowerMonitor */

#ifndef _Included_uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroPowerMonitor
#define _Included_uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroPowerMonitor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroPowerMonitor
 * Method:    ZesInit
 * Signature: ([J)[J
 */
JNIEXPORT jlongArray JNICALL Java_uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroPowerMonitor_ZesInit
  (JNIEnv *, jobject, jlongArray);

/*
 * Class:     uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroPowerMonitor
 * Method:    checkPowerQueryPossible
 * Signature: ([J)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroPowerMonitor_checkPowerQueryPossible
  (JNIEnv *, jobject, jlongArray);

/*
 * Class:     uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroPowerMonitor
 * Method:    getSysmanDevicesToQuery
 * Signature: ([J)[J
 */
JNIEXPORT jlongArray JNICALL Java_uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroPowerMonitor_getSysmanDevicesToQuery
  (JNIEnv *, jobject, jlongArray);

/*
 * Class:     uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroPowerMonitor
 * Method:    getEnergyCounters
 * Signature: (J)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroPowerMonitor_getEnergyCounters
  (JNIEnv *, jobject, jlong);

/*
 * Class:     uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroPowerMonitor
 * Method:    calculatePowerUsage
 * Signature: (Ljava/util/List;Ljava/util/List;)D
 */
JNIEXPORT jdouble JNICALL Java_uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroPowerMonitor_calculatePowerUsage
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroPowerMonitor
 * Method:    zesDeviceEnumPowerDomains_native
 * Signature: (J[I[J)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroPowerMonitor_zesDeviceEnumPowerDomains_1native
  (JNIEnv *, jobject, jlong, jintArray, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
